
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_INIT_LIMIT: 3
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - kafka-net

  kafka1:
    image: confluentinc/cp-server:latest
    hostname: kafka1
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9091:9091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29091,PLAINTEXT_HOST://localhost:9091
    networks:
      - kafka-net

  kafka2:
    image: confluentinc/cp-server:latest
    hostname: kafka2
    container_name: kafka2
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29092,PLAINTEXT_HOST://localhost:9092
    networks:
      - kafka-net

  kafka3:
    image: confluentinc/cp-server:latest
    hostname: kafka3
    container_name: kafka3
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:29093,PLAINTEXT_HOST://localhost:9093
    networks:
      - kafka-net
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9020:8080
    environment:
      AUTH_TYPE: DISABLED
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:29091,kafka2:29092,kafka3:29093
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - kafka-net

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - kafka-net

  user-service:
    build:
      context: .
      args:
        SERVICE_PATH: cmd/userService/main.go
    ports:
      - "8080:8080"
    environment:
      - KAFKA_ADDRESS=kafka1:29091,kafka2:29092,kafka3:29093
      - JWT_SECRET=your_secret_key
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka-net

  product-service:
    build:
      context: .
      args:
        SERVICE_PATH: cmd/productService/main.go
    ports:
      - "8081:8081"
    environment:
      - KAFKA_ADDRESS=kafka1:29091,kafka2:29092,kafka3:29093
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka-net

  recommendation-service:
    build:
      context: .
      args:
        SERVICE_PATH: cmd/recommendationService/main.go
    ports:
      - "8082:8082"
    environment:
      - KAFKA_ADDRESS=kafka1:29091,kafka2:29092,kafka3:29093
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=postgres
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - postgres
      - redis
    networks:
      - kafka-net

  analytics-service:
    build:
      context: .
      args:
        SERVICE_PATH: cmd/analyticsService/main.go
    ports:
      - "8083:8083"
    environment:
      - KAFKA_ADDRESS=kafka1:29091,kafka2:29092,kafka3:29093
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=postgres
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - postgres
    networks:
      - kafka-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"

  grafana:
    image: grafana/grafana-oss:9.4.3
    ports:
      - "13000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:

networks:
  kafka-net:
    driver: bridge