// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/recommendation_db/recommendation_db.go

// Package mock_db is a generated GoMock package.
package mock_db

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDatabaseRecommendationInterface is a mock of DatabaseRecommendationInterface interface.
type MockDatabaseRecommendationInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseRecommendationInterfaceMockRecorder
}

// MockDatabaseRecommendationInterfaceMockRecorder is the mock recorder for MockDatabaseRecommendationInterface.
type MockDatabaseRecommendationInterfaceMockRecorder struct {
	mock *MockDatabaseRecommendationInterface
}

// NewMockDatabaseRecommendationInterface creates a new mock instance.
func NewMockDatabaseRecommendationInterface(ctrl *gomock.Controller) *MockDatabaseRecommendationInterface {
	mock := &MockDatabaseRecommendationInterface{ctrl: ctrl}
	mock.recorder = &MockDatabaseRecommendationInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseRecommendationInterface) EXPECT() *MockDatabaseRecommendationInterfaceMockRecorder {
	return m.recorder
}

// CloseRecommendationDB mocks base method.
func (m *MockDatabaseRecommendationInterface) CloseRecommendationDB() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseRecommendationDB")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseRecommendationDB indicates an expected call of CloseRecommendationDB.
func (mr *MockDatabaseRecommendationInterfaceMockRecorder) CloseRecommendationDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseRecommendationDB", reflect.TypeOf((*MockDatabaseRecommendationInterface)(nil).CloseRecommendationDB))
}

// MigrateRecommendationModels mocks base method.
func (m *MockDatabaseRecommendationInterface) MigrateRecommendationModels() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrateRecommendationModels")
	ret0, _ := ret[0].(error)
	return ret0
}

// MigrateRecommendationModels indicates an expected call of MigrateRecommendationModels.
func (mr *MockDatabaseRecommendationInterfaceMockRecorder) MigrateRecommendationModels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateRecommendationModels", reflect.TypeOf((*MockDatabaseRecommendationInterface)(nil).MigrateRecommendationModels))
}
